version: 2
updates:
  - package-ecosystem: "npm"
    allow:
      - dependency-type: "production"
      - dependency-type: "development"
    directory: "/"
    commit-message:
      prefix: "⬆️ "
      include: "scope"
    schedule:
      interval: "daily"
      time: "07:00"
      timezone: "Europe/Berlin"
