name: "CI"
on: ["push", "pull_request"]
jobs:
  test:
    name: "Test Code (Node ${{ matrix.node }})"
    runs-on: "ubuntu-latest"

    strategy:
      matrix:
        node: ["12", "14", "16"]
      fail-fast: false

    steps:
      - name: "Checkout Repository"
        uses: "actions/checkout@v2"

      - name: "Set Up NodeJS"
        uses: "actions/setup-node@v2"
        with:
          node-version: ${{ matrix.node }}

      - name: "Install Dependencies"
        run: "npm ci"

      - name: "Lint Code"
        if: ${{ matrix.node == '16' }}
        run: "npx eslint -f .github/workflows/formatter.js src/**/*.ts || :"

      - name: "Compile Code"
        run: "npx tsc"

      - name: "Run Tests"
        run: "npx jest"
